import { sql } from "drizzle-orm";
import {
  index,
  pgPolicy,
  pgSequence,
  pgTable,
  text,
  unique,
  uuid,
} from "drizzle-orm/pg-core";
import { timestamps } from "./_shared";
import { users } from "./users";

// Backs the agent_id column default. Per-role sequence; the role-prefixed format
// ("BK-AG-") keeps agent IDs distinct from riders' ("BK-RR-").
export const agentIdSeq = pgSequence("agent_id_seq", { startWith: 100000 });

// An agent's PERSONAL profile (parallel to rider_profiles). Holds only the
// agent's display ID — common fields (wilaya, bank_rib) live on users, and the
// agent's SHOP lives separately in agent_shops.
export const agentProfiles = pgTable(
  "agent_profiles",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    // Human-readable display ID like "BK-AG-100023", auto-generated by the DB.
    agentId: text("agent_id")
      .notNull()
      .unique()
      .default(sql`'BK-AG-' || nextval('agent_id_seq')`),
    // wilaya / bank_rib are common fields and live on users (see users.ts).
    ...timestamps,
  },
  (t) => [
    unique("agent_profiles_user_id_key").on(t.userId),
    index("idx_agent_profiles_user").on(t.userId),
    pgPolicy("agent_profiles_select_own", { for: "select", using: sql`auth.uid() = user_id` }),
    pgPolicy("agent_profiles_update_own", { for: "update", using: sql`auth.uid() = user_id` }),
  ]
);
