import { sql } from "drizzle-orm";
import {
  index,
  pgPolicy,
  pgSequence,
  pgTable,
  text,
  unique,
  uuid,
} from "drizzle-orm/pg-core";
import { timestamps } from "./_shared";
import { users } from "./users";

// Backs the customer_id column default. Per-role sequence; the role-prefixed
// format ("BK-CU-") keeps customer IDs distinct from the other roles'.
export const customerIdSeq = pgSequence("customer_id_seq", { startWith: 100000 });

// A customer's PERSONAL profile (parallel to rider_profiles / agent_profiles).
// Holds only the customer's display ID — common fields (name, wilaya, address)
// live on users.
export const customerProfiles = pgTable(
  "customer_profiles",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    // Human-readable display ID like "BK-CU-100023", auto-generated by the DB.
    customerId: text("customer_id")
      .notNull()
      .unique()
      .default(sql`'BK-CU-' || nextval('customer_id_seq')`),
    ...timestamps,
  },
  (t) => [
    unique("customer_profiles_user_id_key").on(t.userId),
    index("idx_customer_profiles_user").on(t.userId),
    pgPolicy("customer_profiles_select_own", { for: "select", using: sql`auth.uid() = user_id` }),
    pgPolicy("customer_profiles_update_own", { for: "update", using: sql`auth.uid() = user_id` }),
  ]
);
