import { sql } from "drizzle-orm";
import {
  index,
  pgPolicy,
  pgSequence,
  pgTable,
  text,
  unique,
  uuid,
} from "drizzle-orm/pg-core";
import { timestamps } from "./_shared";
import { users } from "./users";

// Backs the merchant_id column default. Per-role sequence; the role-prefixed
// format ("BK-MR-") keeps merchant IDs distinct from riders' ("BK-RR-") and
// agents' ("BK-AG-").
export const merchantIdSeq = pgSequence("merchant_id_seq", { startWith: 100000 });

// A merchant's PERSONAL profile (parallel to rider_profiles / agent_profiles).
// Holds only the merchant's display ID — common fields (wilaya, bank_rib) live
// on users, and a merchant's STORES live separately.
export const merchantProfiles = pgTable(
  "merchant_profiles",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    // Human-readable display ID like "BK-MR-100023", auto-generated by the DB.
    merchantId: text("merchant_id")
      .notNull()
      .unique()
      .default(sql`'BK-MR-' || nextval('merchant_id_seq')`),
    ...timestamps,
  },
  (t) => [
    unique("merchant_profiles_user_id_key").on(t.userId),
    index("idx_merchant_profiles_user").on(t.userId),
    pgPolicy("merchant_profiles_select_own", { for: "select", using: sql`auth.uid() = user_id` }),
    pgPolicy("merchant_profiles_update_own", { for: "update", using: sql`auth.uid() = user_id` }),
  ]
);
