import { sql } from "drizzle-orm";
import {
  index,
  pgPolicy,
  pgSequence,
  pgTable,
  text,
  unique,
  uuid,
} from "drizzle-orm/pg-core";
import { vehicleType } from "./enums";
import { timestamps } from "./_shared";
import { users } from "./users";

// Backs the rider_id column default below. Starts high (100000) so DB-generated
// IDs never collide with the 4-digit random IDs created by app code before this
// became DB-owned. Display IDs are role-prefixed: rider = "BK-RR-".
export const riderIdSeq = pgSequence("rider_id_seq", { startWith: 100000 });

export const riderProfiles = pgTable(
  "rider_profiles",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    // Human-readable display ID like "BK-RR-100001", auto-generated by the DB.
    riderId: text("rider_id")
      .notNull()
      .unique()
      .default(sql`'BK-RR-' || nextval('rider_id_seq')`),
    // wilaya / bank_rib are common fields and live on users (see users.ts).
    vehicleType: vehicleType("vehicle_type"),
    licenseFrontUrl: text("license_front_url"),
    licenseBackUrl: text("license_back_url"),
    ...timestamps,
  },
  (t) => [
    unique("rider_profiles_user_id_key").on(t.userId),
    index("idx_rider_profiles_user").on(t.userId),
    pgPolicy("rider_profiles_select_own", { for: "select", using: sql`auth.uid() = user_id` }),
    pgPolicy("rider_profiles_update_own", { for: "update", using: sql`auth.uid() = user_id` }),
  ]
);
