import { Hono } from "hono";
import { supabaseAdmin } from "../../lib/supabase";
import type { AuthEnv } from "../../middleware/auth";
import { VALID_ROLES, type ServerRole } from "./shared";

const app = new Hono<AuthEnv>();

// ─── Apple OAuth sync ────────────────────────────────────────────────
// Standalone counterpart to POST /google (each social provider is its own
// feature). Same two-step contract — verify the Supabase JWT, return the
// existing profile or create one once a role is chosen — but parses Apple's
// name metadata (`full_name`/`name`), which it only sends on first sign-in.
app.post("/apple", async (c) => {
  const header = c.req.header("Authorization");
  if (!header?.startsWith("Bearer ")) {
    return c.json({ error: "Missing or invalid authorization header" }, 401);
  }
  const token = header.slice(7);

  const {
    data: { user: supaUser },
    error,
  } = await supabaseAdmin.auth.getUser(token);

  if (error || !supaUser) {
    return c.json({ error: "Invalid or expired token" }, 401);
  }

  const { data: existingUser } = await supabaseAdmin
    .from("users")
    .select("*")
    .eq("id", supaUser.id)
    .single();

  // Existing user — just return the profile (ignore any role in body).
  if (existingUser) {
    return c.json({ is_new_user: false, user: existingUser });
  }

  // New user. Parse the optional chosen role.
  const body = await c.req.json().catch(() => ({}) as Record<string, unknown>);
  const role = body.role as string | undefined;

  // Step 1: no role yet — report new, create nothing.
  if (!role) {
    return c.json({ is_new_user: true, user: null });
  }

  // Step 2: create the profile with the chosen role.
  if (!VALID_ROLES.includes(role as ServerRole)) {
    return c.json({ error: `Invalid role: ${role}` }, 400);
  }

  // Apple sends the display name as `full_name`/`name` (only on first auth),
  // not split fields — fall back to splitting it on the first space.
  const meta = supaUser.user_metadata ?? {};
  const fullName = (meta.full_name ?? meta.name) as string | undefined;
  const [firstFromFull, ...restFromFull] = (fullName ?? "").trim().split(/\s+/);
  const firstName = (meta.given_name as string) ?? (firstFromFull || null);
  const lastName =
    (meta.family_name as string) ?? (restFromFull.join(" ") || null);

  const { data: created, error: insertError } = await supabaseAdmin
    .from("users")
    .insert({
      id: supaUser.id,
      email: supaUser.email ?? null,
      first_name: firstName,
      last_name: lastName,
      role: role as ServerRole,
    })
    .select("*")
    .single();

  if (insertError) {
    return c.json({ error: insertError.message }, 400);
  }

  // Create the role-specific profile row (mirrors POST /google and /auth/role).
  if (role === "rider") {
    // rider_id is auto-generated by the DB (sequence-backed default).
    await supabaseAdmin.from("rider_profiles").insert({
      user_id: supaUser.id,
    });
  } else if (role === "agent") {
    await supabaseAdmin.from("agent_shops").insert({
      user_id: supaUser.id,
      shop_name: "",
      open_time: "08:00",
      close_time: "20:00",
      status: "closed",
      latitude: 0,
      longitude: 0,
      rating: 0,
    });
    // agent_id is auto-generated by the DB (sequence-backed default).
    await supabaseAdmin.from("agent_profiles").insert({ user_id: supaUser.id });
  }

  return c.json({ is_new_user: true, user: created });
});

export default app;
