import { Hono } from "hono";
import { supabaseAdmin } from "../../lib/supabase";
import { auth, type AuthEnv } from "../../middleware/auth";
import { selectRoleSchema } from "../../validators/auth";

const app = new Hono<AuthEnv>();

// ─── Select Role (post-registration) ────────────────────────────────
app.post("/role", auth, async (c) => {
  const body = selectRoleSchema.parse(await c.req.json());
  const userId = c.get("userId");

  const { error } = await supabaseAdmin
    .from("users")
    .update({ role: body.role })
    .eq("id", userId);

  if (error) {
    return c.json({ error: error.message }, 400);
  }

  // Create role-specific profile
  if (body.role === "rider") {
    // rider_id is auto-generated by the DB (sequence-backed default).
    await supabaseAdmin.from("rider_profiles").insert({
      user_id: userId,
    });
  } else if (body.role === "agent") {
    await supabaseAdmin.from("agent_shops").insert({
      user_id: userId,
      shop_name: "",
      open_time: "08:00",
      close_time: "20:00",
      status: "closed",
      latitude: 0,
      longitude: 0,
      rating: 0,
    });
    // agent_id is auto-generated by the DB (sequence-backed default).
    await supabaseAdmin.from("agent_profiles").insert({ user_id: userId });
  }

  return c.json({ message: "Role updated", role: body.role });
});

export default app;
