// Shared helpers/constants for the auth endpoints.

import { supabaseAdmin } from "../../lib/supabase";

// Roles a brand-new OAuth user may choose when their profile row is created.
export const VALID_ROLES = ["customer", "rider", "merchant", "agent"] as const;
export type ServerRole = (typeof VALID_ROLES)[number];

// Maps each role to the table(s) holding its role-specific row. Every role now
// has a profile table (rider/agent existed; merchant/customer added in
// migration 00018). The display ID column on each is DB-generated (sequence-
// backed default), so inserting only `user_id` is enough.
const ROLE_PROFILE_TABLE: Record<ServerRole, string> = {
  rider: "rider_profiles",
  agent: "agent_profiles",
  merchant: "merchant_profiles",
  customer: "customer_profiles",
};

/**
 * Idempotently create the role-specific profile row(s) for a user. Safe to call
 * for an existing user (the per-role `UNIQUE(user_id)` makes a duplicate insert
 * a no-op we swallow), so it doubles as a backfill for accounts created before
 * their role table existed. Agents also get an empty `agent_shops` row.
 *
 * Single source of truth for POST /auth/role, /auth/google and /auth/apple —
 * keep role-creation logic here, not duplicated per route.
 */
export async function ensureRoleProfile(
  userId: string,
  role: ServerRole,
): Promise<void> {
  if (role === "agent") {
    // The agent's SHOP is a separate row, created alongside the profile.
    await supabaseAdmin
      .from("agent_shops")
      .upsert(
        {
          user_id: userId,
          shop_name: "",
          open_time: "08:00",
          close_time: "20:00",
          status: "closed",
          latitude: 0,
          longitude: 0,
          rating: 0,
        },
        { onConflict: "user_id", ignoreDuplicates: true },
      );
  }

  // Display ID is auto-generated by the DB; insert only the FK. Upsert with
  // ignoreDuplicates so a re-run (backfill) never errors on the unique user_id.
  await supabaseAdmin
    .from(ROLE_PROFILE_TABLE[role])
    .upsert({ user_id: userId }, { onConflict: "user_id", ignoreDuplicates: true });
}
