import { Hono } from "hono";
import { supabaseAdmin } from "../../lib/supabase";
import type { AuthEnv } from "../../middleware/auth";
import { z } from "zod";

// Only rider-specific fields. Common fields (wilaya, bank_rib) are on users and
// saved via PATCH /auth/profile.
const updateRiderProfileSchema = z.object({
  vehicle_type: z.enum(["bicycle", "motorcycle"]).optional(),
});

const app = new Hono<AuthEnv>();

// ─── Update rider profile ────────────────────────────────────────────
app.patch("/profile", async (c) => {
  const user = c.get("user");
  const body = updateRiderProfileSchema.parse(await c.req.json());

  // Create-if-missing: OAuth users who picked "rider" never went through
  // POST /auth/role, so they may have no rider_profiles row yet. Heal it here.
  const { data: existing } = await supabaseAdmin
    .from("rider_profiles")
    .select("id")
    .eq("user_id", user.id)
    .single();

  let result;
  if (existing) {
    result = await supabaseAdmin
      .from("rider_profiles")
      .update(body)
      .eq("user_id", user.id)
      .select()
      .single();
  } else {
    // rider_id is auto-generated by the DB (sequence-backed default).
    result = await supabaseAdmin
      .from("rider_profiles")
      .insert({ ...body, user_id: user.id })
      .select()
      .single();
  }

  if (result.error || !result.data) {
    return c.json(
      { error: result.error?.message ?? "Could not save rider profile" },
      400,
    );
  }

  return c.json({ profile: result.data });
});

export default app;
